# r= input()
# print("I am ",r)

x= input("Enter first number: ")
y = input("Enter second number: ")
# print(x+y)
print(int(x) + int(y))
print(int(x) - int(y))
print(int(x) * int(y))
print(int(x) / int(y))
print(int(x) // int(y))
print(int(x) % int(y))
print(int(x) ** int(y))